name: Build Screensaver Card

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup di Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 3. Installazione delle dipendenze
      - name: Install dependencies
        run: npm install

      # 4. Build del progetto con Rollup
      - name: Build project with Rollup
        run: npm run build

      # 5. Aggiungi il comando di debug per elencare i file nella cartella dist
      - name: List dist contents
        run: ls -la dist/

      # 6. Carica gli artifact della build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screensaver-card-build
          path: dist/
