name: Build Screensaver Card

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Fix Rollup permissions
        run: chmod +x ./node_modules/.bin/rollup  # Imposta i permessi corretti per Rollup

      - name: Build project with Rollup
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screensaver-card-build
          path: dist/
